FROM alpine:3.18.3 as base

FROM base as download


RUN chmod +x start.sh

CMD ["sh", "start.sh"]

# Set permissions for the directory
RUN chown -R www-data:www-data public/thumbnail
RUN chmod -R 775 public/thumbnail